- name: Fix Firewall Vulnerabilities
  hosts: inner-firewall
  vars_files:
    - ./var/ifirewall_var.yml
  tasks:
    - name: Enter enable mode
      cisco.ios.ios_command:
        commands:
          - command: enable
      vars:
        ansible_become_pass: Dalhousie@09876
    - name: Deny ICMP Packets
      cisco.ios.ios_command:
        commands:
          - command: policy-map global_policy
          - command: class inspection_default
          - command: inspect icmp
          - command: exit
          - command: exit
          - command: icmp permit host 188.172.40.66 echo outside
          - command: icmp permit host 188.172.40.66 echo inside
          - command: icmp deny any outside  
    - name: Enable threat detection and block port scanning
      cisco.ios.ios_command:
        commands:
          - command: threat-detection basic-threat
          - command: threat-detection scanning-threat shun
    - name: Disable ssh version 1
      cisco.ios.ios_command:
        commands:
          - command: ssh version 2
    - name: Disable unused services and ports
      cisco.ios.ios_command:
        commands:
          - command: no http server Enable
          - command: no telnet 0.0.0.0 0.0.0.0 inside
          - command: no snmp-server enable
    - name: Prevent TCP DoS attack
      cisco.ios.ios_command:
        commands:
          - command: tcp-map tcp-dos-normal
          - command: no check-retransmission
          - command: no checksum-verification
          - command: exceed-mss allow
          - command: queue-limit 0 timeout 4
          - command: reserved-bits allow
          - command: syn-data allow
          - command: synack-data drop
          - command: invalid-ack drop
          - command: seq-past-window drop
          - command: tcp-options range 6 7 clear
          - command: class-map tcp-class
          - command: match any
          - command: policy-map tcp-policy
          - command: class tcp-class
          - command: set connection advanced-options tcp-dos-normal
          - command: service-policy tcp-policy interface outside
          - comamnd: exit
