- name: Fix Router Vulnerabilities
  hosts: proxy-router
  become: true
  vars_files:
    - ./var/router_var.yml
  tasks:
    - name: Enter enable mode
      cisco.ios.ios_command:
        commands:
         - command: enable
      vars:
        ansible_become_pass: Dalhousie@09876
    - name: Disable IP SSH ver 1
      cisco.ios.ios_command:
        commands:
          - command: config t
          - command: no ip ssh ver
    - name: Disable unused services
      cisco.ios.ios_command:
        commands:
        - command: config t
        - command: no boot network
        - command: no ip boot server
        - command: no ip bootp server
        - command: no ip domain-lookup
        - command: no ip identd
        - command: no ip finger
        - command: no ip http server
        - command: no ip rcmd rcp-enable
        - command: no ip rcmd rsh-enable
        - command: no service config
        - command: no service finger
        - command: no service tcp-small-servers
        - command: no service udp-small-servers
        - command: no service pad
        - command: exit